name: BXRL78FS510 CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  cloud-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fae-emea/bxrl78fs:5.10.5
        
    steps:      
      - name: Checkout project
        uses: actions/checkout@v4

      - name: CMake - Configure
        run: cmake -S. -Bbuild -GNinja
        
      - name: CMake - Build
        run: cmake --build build -j `nproc` --verbose

      - name: Upload ELF             
        uses: actions/upload-artifact@v4
        with:
          name: tutorial.elf
          path: build/*.elf
          if-no-files-found: error

      - name: Upload binary             
        uses: actions/upload-artifact@v4
        with:
          name: tutorial.hex
          path: build/*.hex
          if-no-files-found: error
